[build]
  publish = "public"
  command = "pip install -r requirements.txt && flask run"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-python"
