[build]
  command = "pip install -r requirements.txt"
  publish = "app"  # Adjust this based on your Flask app structure
  base = ""  # Adjust if your Flask app is in a subdirectory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
